Google mapでショップの位置情報入力
denkikairo/shop_event_schedule pull request #10
Opened 2019-11-28 07:05 UTC by denkikairo

### 概要
shop userがアカウント登録した後、google mapを利用して位置情報の入力を行うようにする。

### 確認方法
サインアップした後位置情報を入力するためのshops info edit画面が表示
google map のautocompleteを使用して、入力候補から選べるようにする
![image](https://user-images.githubusercontent.com/39436891/69784144-71618700-11f8-11ea-987e-78704f1ba4af.png)
候補から選ぶと位置情報が自動入力される
![image](https://user-images.githubusercontent.com/39436891/69784160-7fafa300-11f8-11ea-96fb-24d3211cb2fc.png)
shop info show画面
![image](https://user-images.githubusercontent.com/39436891/69784311-d4ebb480-11f8-11ea-8070-f41f84d637ba.png)

2019-11-28 07:10 UTC, yuji91 commented on app/controllers/application_controller.rb
> +    end
`return`などのガード節を使ってif文のネストを1段階までに減らしましょう！

2019-11-28 07:12 UTC, yuji91 commented on app/assets/javascripts/edit_map_info.js
> +// generated by coffee-script 1.9.2
ここのコメントは不要なので消した方が良いですね！

2019-11-28 07:16 UTC, yuji91 commented on app/assets/javascripts/edit_map_info.js
> +  var placeSearch, autocomplete;
`placeSearch`はここでしか使用していないので、宣言する必要はないと思います。
恐らくcoffee_scriptのコードをそのままJavascriptに変換したコードのため、このような記載になっているものと予想します。（coffeeでは事前に全ての変数を宣言する必要があります。）

2019-11-28 07:18 UTC, yuji91 commented on app/assets/javascripts/edit_map_info.js
> +  }
`var`は代入しているか、再宣言しているかで`let`と`const`に書き換えてください！
（ほとんどがconstの定数で十分だと思います。）

2019-11-28 07:18 UTC, yuji91 commented on app/assets/stylesheets/application.scss
> +@import "custom";  //devise フラッシュメッセージのスタイル
細かいですがここもシングルクォートで統一した方が読みやすいですね。

2019-11-28 07:20 UTC, yuji91 commented on app/controllers/shops/infos_controller.rb
> +  before_action :set_shop, only: %i[show edit update]
Controllerのコールバックの後は1行改行した方が見やすいと思います。

2019-11-28 07:26 UTC, yuji91 commented on app/views/shops/infos/edit.html.slim
> +      #edit_map_info.mb-3 style="width: 800px; height: 400px;", class:'mb-3'
ここもシングルクォートにした方がいいですね。

2019-11-28 07:26 UTC, yuji91 commented on app/views/shops/infos/edit.html.slim
> +          = f.submit class: "btn btn-primary mb-3"
ここもシングルクォートに統一しましょう。

2019-11-28 07:27 UTC, yuji91 commented on app/views/shops/infos/show.html.slim
> +      #map.mb-3 style="width: 800px; height: 400px;"
このファイルもシングルクォートに統一しましょう。

2019-11-28 07:28 UTC, yuji91 commented on app/views/shops/infos/show.html.slim
> +          th scope="row"  Address
rowの直後はスペース1つで良いと思います。

2019-11-28 07:35 UTC, yuji91 commented on app/views/layouts/application.html.slim
> +    script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"
シングルに統一しておきましょう！

2019-11-28 07:43 UTC, DaichiSaito commented on app/views/shops/infos/edit.html.slim
> +          = f.text_field :email, class:'form-control mb-3'
メールアドレスは`f.email_field`で。

2019-11-28 07:44 UTC, DaichiSaito commented on app/views/shops/infos/edit.html.slim
> +            = f.text_field :latitude, class:'form-control mb-3'
数値は`f.number_field`で。

2019-11-28 08:11 UTC, yuji91 commented on app/views/shops/_infowindow.html.slim
> += link_to "拡大地図を表示" ,"https://maps.google.co.jp/maps?q=loc:#{shop.latitude},#{shop.longitude}&iwloc=J",target: "_blank"
`,` の後にはスペースを入れて見やすくしましょう！

2019-11-28 08:11 UTC, yuji91 requested changes
確認してコメントしました！

2019-11-28 10:50 UTC, denkikairo commented on app/controllers/application_controller.rb
> +    end
ifのネストなしの方が見やすいです

2019-11-28 10:50 UTC, denkikairo commented on app/assets/javascripts/edit_map_info.js
> +  var placeSearch, autocomplete;
なくても問題なしでした

2019-12-02 07:37 UTC, denkikairo commented on app/assets/javascripts/edit_map_info.js
> +  }
一つだけvarでないと動きませんでしたが、それ以外はconstで大丈夫でした。
myLatLngという変数だけ複数回宣言しているため、varじゃないとダメでした。

2019-12-02 08:33 UTC, yuji91 commented on spec/system/shop_spec.rb
> +        expect(page).to have_content 'Signed in successfully.'
フラッシュメッセージの以外にも、遷移先のcurrent_pathも確認して欲しいです！

2019-12-02 08:34 UTC, yuji91 commented on spec/factories/shop.rb
> +    email { 'example@gmail.com' }
確実に存在しないことが保証されているドメイン `@example.com` を使いましょう！
https://blog.ko31.com/201304/sample-domain-example/

2019-12-02 09:44 UTC, yuji91 commented on spec/system/shop_spec.rb
> +        fill_in 'Email', with: 'example@gmail.com'
ここも存在しないことが保証されているドメインに変更をお願いします。

2019-12-02 09:57 UTC, yuji91 commented on spec/system/shop_spec.rb
> +  end
`'ShopInfo編集画面'`のテストケースがあるのに`'ShopInfo登録画面'`のテストケースがない点は違和感があります。

APIの要因でテストケースが作成できないなどの場合は `it 'ShopInfo登録が成功すること' do`とテストケースは作成してコメントアウトするか、Pending状態にして考慮漏れでないという意図を伝えた方が良いです。

2019-12-02 09:59 UTC, yuji91 commented on spec/system/shop_spec.rb
> +  end
shopのテストに関係がないテストは別のspecファイルに切り出した方が良いです。

ログイン: UserSession or Login
サインアップ: User or Signup

2019-12-02 10:07 UTC, yuji91 requested changes
レビュアーが動作確認を進めるための情報をREADMEに記載してください。
- [x] 利用しているGoogleAPIの種類を教えてください。

- [x] GoogleAPI利用のための簡単な手順をREADMEに記載してください。
（Rails.application.credentials[:google_api_key]を設定する手順）

- [x] 最低限のSeedデータを登録しておいてください（今回のケースであれば User）

2019-12-05 03:41 UTC, denkikairo commented on spec/factories/shop.rb
> +    email { 'example@gmail.com' }
`305db32`で修正しました

2019-12-05 03:42 UTC, denkikairo commented on spec/system/shop_spec.rb
> +        fill_in 'Email', with: 'example@gmail.com'
`305db32`で修正しました

2019-12-05 03:53 UTC, denkikairo commented on spec/system/shop_spec.rb
> +        expect(page).to have_content 'Signed in successfully.'
`473a918`で修正しました

2019-12-05 04:39 UTC, denkikairo commented on spec/system/shop_spec.rb
> +        fill_in 'Email', with: 'example@gmail.com'
305db32 で修正しました

2019-12-05 04:47 UTC, denkikairo commented on spec/system/shop_spec.rb
> +        expect(page).to have_content 'Signed in successfully.'
473a9189670e168ac514db935d131c31527f3212

2019-12-05 04:48 UTC, denkikairo commented on spec/system/shop_spec.rb
> +        expect(page).to have_content 'Signed in successfully.'
473a9189670e168ac514db935d131c31527f3212
で修正しました

2019-12-05 04:48 UTC, denkikairo commented on spec/factories/shop.rb
> +    email { 'example@gmail.com' }
305db32502a6af52d99f2fa84c161d466adcba2e
で修正しました

2019-12-05 04:48 UTC, denkikairo commented on spec/system/shop_spec.rb
> +        fill_in 'Email', with: 'example@gmail.com'
305db32502a6af52d99f2fa84c161d466adcba2e
で修正しました

2019-12-05 04:52 UTC, denkikairo commented on spec/system/shop_spec.rb
> +  end
shop_userの下にshopモデルを作るという設計方法もあるということがわかりました。
こうすると一つのshopを複数の担当者が管理できますね(shop has_many: shop_user)。

2019-12-05 07:04 UTC, denkikairo commented
> レビュアーが動作確認を進めるための情報をREADMEに記載してください。
> 
> * [x]  利用しているGoogleAPIの種類を教えてください。
> * [x]  GoogleAPI利用のための簡単な手順をREADMEに記載してください。
>   （Rails.application.credentials[:google_api_key]を設定する手順）
> * [x]  最低限のSeedデータを登録しておいてください（今回のケースであれば User）

- READMEにapi情報の追加
https://github.com/denkikairo/shop_event_schedule/blob/develop/README.md
- seedの登録
0ae164094057360870fcdde7eb6605e42d6e11b4

2019-12-05 07:19 UTC, yuji91 commented on db/seeds.rb
> +              password_confirmation:  "password",
式展開しない文字列なのでシングルにしておきましょうか

2019-12-05 07:19 UTC, yuji91 commented on spec/factories/shop.rb
> +    password_confirmation { "password" }
ここもシングルでお願いします。

2019-12-05 07:20 UTC, yuji91 commented on spec/factories/shop.rb
> +    address { '日本、〒104-0061 東京都中央区銀座３丁目５−１２ サヱグサビル 本館' }
テストデータには極力外部の情報を使わない方が良いですね。
今回はRUNTEQの情報を使ってください。

2019-12-05 07:21 UTC, yuji91 requested changes
コメントしました！

2019-12-05 07:30 UTC, denkikairo commented on db/seeds.rb
> +              password_confirmation:  "password",
07f71abd94cd7b15500d1bb96aa989044e7c8074
で修正

2019-12-05 07:31 UTC, denkikairo commented on spec/factories/shop.rb
> +    password_confirmation { "password" }
07f71abd94cd7b15500d1bb96aa989044e7c8074
で修正

2019-12-05 07:31 UTC, denkikairo commented on spec/factories/shop.rb
> +    address { '日本、〒104-0061 東京都中央区銀座３丁目５−１２ サヱグサビル 本館' }
18e0d5c03ce2ef7f5ffdf5447fe73205524f59cf
で修正

2019-12-05 07:34 UTC, yuji91 requested changes
https://github.com/denkikairo/shop_event_schedule/pull/10/files#r351628290 の対応もお願いします！

2019-12-05 07:59 UTC, denkikairo commented on app/views/shops/infos/edit.html.slim
> +          = f.text_field :email, class:'form-control mb-3'
見落としていました。
9b541574a9da285ad9592c539beb9f6f89e6031d
で修正しました。

2019-12-05 08:00 UTC, yuji91 approved these changes

2019-12-05 08:02 UTC, merged